basePath: /api/v1
definitions:
  types.Category:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Personal Computer Maintenance Management System REST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PersonaCMMS API
  version: "1.0"
paths:
  /categories:
    post:
      consumes:
      - application/json
      description: Create a category
      parameters:
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Category'
      summary: Create a category
  /categories/{categoryTitle}:
    delete:
      description: Delete a category
      responses:
        "204":
          description: No Content
      summary: Delete a category
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
