## Config file for [Air](https://github.com/air-verse/air) in TOML format

## Working directory
## . or absolute path, please note that the directories following must be under root.
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  ## Just plain old shell command. You could use `make` as well.
  cmd = "make build-linux"
  ## Binary file yields from `cmd`.
  bin = "./bin/personacmms"
  ## Watch these filename extensions.
  include_ext = ["go", "tpl", "tmpl", "html"]
  ## Ignore these filename extensions or directories.
  exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
  ## Exclude specific regular expressions.
  exclude_regex = ["_test\\.go"]
  ## Exclude unchanged files.
  exclude_unchanged = false
  ## Follow symlink for directories
  follow_symlink = false
  ## This log file places in your tmp_dir.
  log = "build-errors.log"
  ## Poll files for changes instead of using fsnotify.
  poll = false
  ## Poll interval (defaults to the minimum interval of 500ms).
  poll_interval = 0 # ms
  ## It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  ## Stop running old binary when build errors occur.
  stop_on_error = false
  ## Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  ## Delay after sending Interrupt signal
  kill_delay = "0s"
  ## Rerun binary or not
  rerun = false
  ## Delay after each execution
  rerun_delay = 500
  ## Array of commands to run before each build
  # pre_cmd = ["echo 'hello air' > pre_cmd.txt"]
  ## Array of commands to run after ^C
  # post_cmd = ["echo 'hello air' > post_cmd.txt"]
  ## Customize binary, can setup environment variables when run your app.
  # full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  ## Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  # args_bin = ["hello", "world"]
  ## Watch these directories if you specified.
  # include_dir = []
  ## Watch these files.
  # include_file = []
  ## Exclude files.
  # exclude_file = []
  

[color]
  ## Customize each part's color. If no color found, use the raw app log.
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  ## Only show main log (silences watcher, build, runner)
  main_only = false
  ## silence all logs produced by air 
  silent = false
  ## Show log time
  time = false

[misc]
  ## Delete tmp directory on exit
  clean_on_exit = false

[proxy]
  ## Enable live-reloading on the browser.
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
