// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/asset-task-consumables": {
            "post": {
                "description": "Create a relationship between an asset task and a consumable with json body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a relationship between an asset task and a consumable with json body",
                "parameters": [
                    {
                        "description": "Asset Task Consumable object",
                        "name": "assetTaskConsumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                }
            }
        },
        "/asset-task-tools": {
            "post": {
                "description": "Create a relationship between an asset task and a tool with json body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a relationship between an asset task and a tool with json body",
                "parameters": [
                    {
                        "description": "Asset Task Tool object",
                        "name": "assetTaskTool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskTool"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskTool"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "List all categories",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Category"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create an asset category",
                "parameters": [
                    {
                        "description": "Category object",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Category"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Category"
                        }
                    }
                }
            }
        },
        "/categories/{categoryTitle}": {
            "get": {
                "description": "Get a category",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Title",
                        "name": "categoryTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Category"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Title",
                        "name": "categoryTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category object",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Category"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Category"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete a category",
                "summary": "Delete an asset category",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Title",
                        "name": "categoryTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/consumables": {
            "get": {
                "description": "List all consumables",
                "produces": [
                    "application/json"
                ],
                "summary": "List consumables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Consumable"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a consumable",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a consumable",
                "parameters": [
                    {
                        "description": "Consumable object",
                        "name": "consumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Consumable"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Consumable"
                        }
                    }
                }
            }
        },
        "/consumables/{consumableId}": {
            "put": {
                "description": "Update an asset task consumable with json body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset task consumable with json body",
                "parameters": [
                    {
                        "description": "Asset Task Consumable object",
                        "name": "assetTaskConsumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                }
            }
        },
        "/consumables/{consumableTitle}": {
            "get": {
                "description": "Get a consumable",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a consumable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Consumable"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a consumable",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a consumable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Consumable object",
                        "name": "consumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Consumable"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Consumable"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a consumable",
                "summary": "Delete a consumable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "description": "List all groups",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Group"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create an asset group",
                "parameters": [
                    {
                        "description": "Group object",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Group"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Group"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}": {
            "get": {
                "description": "Get a group",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Group"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Group object",
                        "name": "group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Group"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Group"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a group",
                "summary": "Delete an asset group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks": {
            "get": {
                "description": "List all asset tasks",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.AssetTask"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create an asset task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create an asset task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset Task object",
                        "name": "assetTask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTask"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTask"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks/{assetTaskId}": {
            "get": {
                "description": "Get an asset task",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTask"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an asset task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset Task object",
                        "name": "assetTask",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTask"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an asset task",
                "summary": "Delete an asset task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks/{assetTaskId}/consumables": {
            "get": {
                "description": "List all asset task consumables",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset task consumables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task ID",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.AssetTaskConsumable"
                            }
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks/{assetTaskId}/consumables/{consumableId}": {
            "get": {
                "description": "Get an asset task consumable",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset task consumable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task ID",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an asset task consumable with path parameters",
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset task consumable with path parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task ID",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset Task Consumable object",
                        "name": "assetTaskConsumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumableForPath"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a relationship between an asset task and a consumable with path parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a relationship between an asset task and a consumable with path parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task ID",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Asset Task Consumable object",
                        "name": "assetTaskConsumable",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumableForPath"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskConsumable"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an asset task consumable",
                "summary": "Delete an asset task consumable",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task ID",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Consumable ID",
                        "name": "consumableId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks/{assetTaskId}/tools": {
            "get": {
                "description": "List all asset task tools",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset task tools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.AssetTaskTool"
                            }
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/asset-tasks/{assetTaskId}/tools/{toolId}": {
            "get": {
                "description": "Get an asset task tool",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset task tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tool Id",
                        "name": "toolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskTool"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a relationship between an asset task and a tool with path parameters",
                "produces": [
                    "application/json"
                ],
                "summary": "Create a relationship between an asset task and a tool with path parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tool Id",
                        "name": "toolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.AssetTaskTool"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a relationship between an asset task and a tool",
                "summary": "Delete a relationship between an asset task and a tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tool Id",
                        "name": "toolId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/date-triggers": {
            "get": {
                "description": "List date triggers",
                "produces": [
                    "application/json"
                ],
                "summary": "List date triggers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.DateTrigger"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a date trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a date trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Date Trigger object",
                        "name": "dateTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DateTrigger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.DateTrigger"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/date-triggers/{dateTriggerId}": {
            "get": {
                "description": "Get a date trigger",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a date trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date Trigger Id",
                        "name": "dateTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DateTrigger"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a date trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a date trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date Trigger Id",
                        "name": "dateTriggerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Date Trigger object",
                        "name": "dateTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.DateTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DateTrigger"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a date trigger",
                "summary": "Delete a date trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date Trigger Id",
                        "name": "dateTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/time-triggers": {
            "get": {
                "description": "List all time triggers",
                "produces": [
                    "application/json"
                ],
                "summary": "List time triggers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.TimeTrigger"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a time trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a time trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Time Trigger object",
                        "name": "timeTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.TimeTrigger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.TimeTrigger"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/time-triggers/{timeTriggerId}": {
            "get": {
                "description": "Get a time trigger",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a time trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time Trigger Id",
                        "name": "timeTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.TimeTrigger"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a time trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a time trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time Trigger Id",
                        "name": "timeTriggerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Time Trigger object",
                        "name": "timeTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.TimeTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.TimeTrigger"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a time trigger",
                "summary": "Delete a time trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Time Trigger Id",
                        "name": "timeTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/usage-triggers": {
            "get": {
                "description": "List usage triggers",
                "produces": [
                    "application/json"
                ],
                "summary": "List usage triggers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.UsageTrigger"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a usage trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a usage trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Usage Trigger object",
                        "name": "usageTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UsageTrigger"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.UsageTrigger"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/usage-triggers/{usageTriggerId}": {
            "get": {
                "description": "Get a usage trigger",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a usage trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Usage Trigger Id",
                        "name": "usageTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UsageTrigger"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a usage trigger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a usage trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Usage Trigger Id",
                        "name": "usageTriggerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Usage Trigger object",
                        "name": "usageTrigger",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UsageTrigger"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.UsageTrigger"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a usage trigger",
                "summary": "Delete a usage trigger",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Title",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Usage Trigger Id",
                        "name": "usageTriggerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/work-orders": {
            "get": {
                "description": "List all asset task work orders",
                "produces": [
                    "application/json"
                ],
                "summary": "List asset task work orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.WorkOrder"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a work order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a work order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Work Order object",
                        "name": "workOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.WorkOrder"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.WorkOrder"
                        }
                    }
                }
            }
        },
        "/groups/{groupTitle}/assets/{assetTitle}/tasks/{assetTaskId}/work-orders/{workOrderId}": {
            "get": {
                "description": "Get an asset task work order",
                "produces": [
                    "application/json"
                ],
                "summary": "Get an asset task work order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Work Order Id",
                        "name": "workOrderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkOrder"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an asset task work order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update an asset task work order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Work Order Id",
                        "name": "workOrderId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Work Order object",
                        "name": "workOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.WorkOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.WorkOrder"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an asset task work order",
                "summary": "Delete an asset task work order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group Title",
                        "name": "groupTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Id",
                        "name": "assetTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset Task Id",
                        "name": "assetTaskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Work Order Id",
                        "name": "workOrderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "List all tasks",
                "produces": [
                    "application/json"
                ],
                "summary": "List tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Task"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a task",
                "parameters": [
                    {
                        "description": "Task object",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Task"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Task"
                        }
                    }
                }
            }
        },
        "/tasks/{taskTitle}": {
            "get": {
                "description": "Get a task",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Title",
                        "name": "taskTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Task"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Title",
                        "name": "taskTitle",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task object",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Task"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "description": "Delete a task",
                "summary": "Delete a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Title",
                        "name": "taskTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/time-units": {
            "get": {
                "description": "List all time units",
                "produces": [
                    "application/json"
                ],
                "summary": "List time units",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.TimeUnit"
                            }
                        }
                    }
                }
            }
        },
        "/tools": {
            "get": {
                "description": "List all tools",
                "produces": [
                    "application/json"
                ],
                "summary": "List tools",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Tool"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a tool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create a tool",
                "parameters": [
                    {
                        "description": "Tool object",
                        "name": "tool",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Tool"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.Tool"
                        }
                    }
                }
            }
        },
        "/tools/{toolTitle}": {
            "get": {
                "description": "Get a tool",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tool Title",
                        "name": "toolTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Tool"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a tool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tool Title",
                        "name": "toolTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Tool"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a tool",
                "summary": "Delete a tool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tool Title",
                        "name": "toolTitle",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/usage-units": {
            "get": {
                "description": "List all usage units",
                "produces": [
                    "application/json"
                ],
                "summary": "List usage units",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.UsageUnit"
                            }
                        }
                    }
                }
            }
        },
        "/work-order-statuses": {
            "get": {
                "description": "List all work order statuses",
                "produces": [
                    "application/json"
                ],
                "summary": "List work order statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.WorkOrderStatus"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.AssetTask": {
            "type": "object",
            "properties": {
                "taskId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "uniqueInstructions": {
                    "type": "string"
                }
            }
        },
        "types.AssetTaskConsumable": {
            "type": "object",
            "required": [
                "assetTaskId",
                "consumableId",
                "quantityNote"
            ],
            "properties": {
                "assetTaskId": {
                    "type": "string"
                },
                "consumableId": {
                    "type": "string"
                },
                "quantityNote": {
                    "type": "string"
                }
            }
        },
        "types.AssetTaskConsumableForPath": {
            "type": "object",
            "required": [
                "quantityNote"
            ],
            "properties": {
                "quantityNote": {
                    "type": "string"
                }
            }
        },
        "types.AssetTaskTool": {
            "type": "object",
            "required": [
                "assetTaskId",
                "toolId"
            ],
            "properties": {
                "assetTaskId": {
                    "type": "string"
                },
                "toolId": {
                    "type": "string"
                }
            }
        },
        "types.Category": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.Consumable": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "types.DateTrigger": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                }
            }
        },
        "types.Group": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "types.Task": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.TimeTrigger": {
            "type": "object",
            "required": [
                "quantity",
                "time_unit"
            ],
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "time_unit": {
                    "type": "string"
                }
            }
        },
        "types.TimeUnit": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "types.Tool": {
            "type": "object",
            "required": [
                "size",
                "title"
            ],
            "properties": {
                "size": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.UsageTrigger": {
            "type": "object",
            "required": [
                "quantity",
                "usage_unit"
            ],
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "usage_unit": {
                    "type": "string"
                }
            }
        },
        "types.UsageUnit": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "types.WorkOrder": {
            "type": "object",
            "required": [
                "statusId"
            ],
            "properties": {
                "completedDate": {
                    "type": "string"
                },
                "cumulativeHours": {
                    "type": "integer"
                },
                "cumulativeMiles": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "statusId": {
                    "type": "string"
                }
            }
        },
        "types.WorkOrderStatus": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PersonaCMMS API",
	Description:      "This is the Personal Computer Maintenance Management System REST API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
