basePath: /api/v1
definitions:
  types.Category:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  types.Consumable:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.Group:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.PreventativeTask:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  types.TimeUnit:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.UsageUnit:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.WorkOrderStatus:
    properties:
      title:
        type: string
    required:
    - title
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Personal Computer Maintenance Management System REST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PersonaCMMS API
  version: "1.0"
paths:
  /categories:
    get:
      description: List all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Category'
            type: array
      summary: List asset categories
    post:
      consumes:
      - application/json
      description: Create a category
      parameters:
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Category'
      summary: Create an asset category
  /categories/{categoryTitle}:
    delete:
      description: Delete a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete an asset category
    get:
      description: Get a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Category'
      summary: Get an asset category
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Category'
        "500":
          description: Internal Server Error
      summary: Update an asset category
  /consumables:
    get:
      description: List all consumables
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Consumable'
            type: array
      summary: List consumables
    post:
      consumes:
      - application/json
      description: Create a consumable
      parameters:
      - description: Consumable object
        in: body
        name: consumable
        required: true
        schema:
          $ref: '#/definitions/types.Consumable'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Consumable'
      summary: Create a consumable
  /consumables/{consumableTitle}:
    delete:
      description: Delete a consumable
      parameters:
      - description: Consumable ID
        in: path
        name: consumableTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete a consumable
    get:
      description: Get a consumable
      parameters:
      - description: Consumable ID
        in: path
        name: consumableTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Consumable'
      summary: Get a consumable
    put:
      consumes:
      - application/json
      description: Update a consumable
      parameters:
      - description: Consumable ID
        in: path
        name: consumableTitle
        required: true
        type: string
      - description: Consumable object
        in: body
        name: consumable
        required: true
        schema:
          $ref: '#/definitions/types.Consumable'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Consumable'
      summary: Update a consumable
  /groups:
    get:
      description: List all groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Group'
            type: array
      summary: List asset groups
    post:
      consumes:
      - application/json
      description: Create a group
      parameters:
      - description: Group object
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/types.Group'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Group'
      summary: Create an asset group
  /groups/{groupTitle}:
    delete:
      description: Delete a group
      parameters:
      - description: Group Title
        in: path
        name: groupTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete an asset group
    get:
      description: Get a group
      parameters:
      - description: Group Title
        in: path
        name: groupTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Group'
      summary: Get an asset group
    put:
      consumes:
      - application/json
      description: Update a group
      parameters:
      - description: Group Title
        in: path
        name: groupTitle
        required: true
        type: string
      - description: Group object
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/types.Group'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Group'
      summary: Update an asset group
  /preventativeTasks:
    get:
      description: List all preventativeTasks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.PreventativeTask'
            type: array
      summary: List preventativeTasks
    post:
      consumes:
      - application/json
      description: Create a preventativeTask
      parameters:
      - description: PreventativeTask object
        in: body
        name: preventativeTask
        required: true
        schema:
          $ref: '#/definitions/types.PreventativeTask'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.PreventativeTask'
      summary: Create a preventativeTask
  /preventativeTasks/{preventativeTaskTitle}:
    delete:
      description: Delete a preventativeTask
      parameters:
      - description: PreventativeTask Title
        in: path
        name: preventativeTaskTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete a preventativeTask
    get:
      description: Get a preventativeTask
      parameters:
      - description: PreventativeTask Title
        in: path
        name: preventativeTaskTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.PreventativeTask'
      summary: Get a preventativeTask
    put:
      consumes:
      - application/json
      description: Update a preventativeTask
      parameters:
      - description: PreventativeTask Title
        in: path
        name: preventativeTaskTitle
        required: true
        type: string
      - description: PreventativeTask object
        in: body
        name: preventativeTask
        required: true
        schema:
          $ref: '#/definitions/types.PreventativeTask'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Update a preventativeTask
  /time-units:
    get:
      description: List all time units
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.TimeUnit'
            type: array
      summary: List time units
    post:
      consumes:
      - application/json
      description: Create a time unit
      parameters:
      - description: Time Unit object
        in: body
        name: timeUnit
        required: true
        schema:
          $ref: '#/definitions/types.TimeUnit'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.TimeUnit'
      summary: Create a time unit
  /time-units/{timeUnitTitle}:
    delete:
      description: Delete a time unit
      parameters:
      - description: Time Unit Title
        in: path
        name: timeUnitTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete a time unit
    get:
      description: Get a time unit
      parameters:
      - description: Time Unit Title
        in: path
        name: timeUnitTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TimeUnit'
      summary: Get a time unit
    put:
      consumes:
      - application/json
      description: Update a time unit
      parameters:
      - description: Time Unit Title
        in: path
        name: timeUnitTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.TimeUnit'
      summary: Update a time unit
  /usage-units:
    get:
      description: List all usage units
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.UsageUnit'
            type: array
      summary: List usage units
    post:
      consumes:
      - application/json
      description: Create a usage unit
      parameters:
      - description: Usage Unit object
        in: body
        name: usageUnit
        required: true
        schema:
          $ref: '#/definitions/types.UsageUnit'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.UsageUnit'
      summary: Create a usage unit
  /usage-units/{usageUnitTitle}:
    delete:
      description: Delete a usage unit
      parameters:
      - description: Usage Unit Title
        in: path
        name: usageUnitTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete a usage unit
    get:
      description: Get a usage unit
      parameters:
      - description: Usage Unit Title
        in: path
        name: usageUnitTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.UsageUnit'
      summary: Get a usage unit
    put:
      consumes:
      - application/json
      description: Update a usage unit
      parameters:
      - description: Usage Unit Title
        in: path
        name: usageUnitTitle
        required: true
        type: string
      responses: {}
      summary: Update a usage unit
  /work-order-statuses:
    get:
      description: List all work order statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.WorkOrderStatus'
            type: array
      summary: List work order statuses
    post:
      consumes:
      - application/json
      description: Create a work order status
      parameters:
      - description: Work Order Status object
        in: body
        name: workOrderStatus
        required: true
        schema:
          $ref: '#/definitions/types.WorkOrderStatus'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.WorkOrderStatus'
      summary: Create a work order status
  /work-order-statuses/{workOrderStatusTitle}:
    delete:
      description: Delete a work order status
      parameters:
      - description: Work Order Status Title
        in: path
        name: workOrderStatusTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete a work order status
    get:
      description: Get a work order status
      parameters:
      - description: Work Order Status Title
        in: path
        name: workOrderStatusTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.WorkOrderStatus'
      summary: Get a work order status
    put:
      consumes:
      - application/json
      description: Update a work order status
      parameters:
      - description: Work Order Status Title
        in: path
        name: workOrderStatusTitle
        required: true
        type: string
      - description: Work Order Status object
        in: body
        name: workOrderStatus
        required: true
        schema:
          $ref: '#/definitions/types.WorkOrderStatus'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.WorkOrderStatus'
      summary: Update a work order status
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
