basePath: /api/v1
definitions:
  types.Category:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  types.Group:
    properties:
      title:
        type: string
    required:
    - title
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the Personal Computer Maintenance Management System REST API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: PersonaCMMS API
  version: "1.0"
paths:
  /categories:
    get:
      description: List all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Category'
            type: array
      summary: List asset categories
    post:
      consumes:
      - application/json
      description: Create a category
      parameters:
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Category'
      summary: Create an asset category
  /categories/{categoryTitle}:
    delete:
      description: Delete a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete an asset category
    get:
      description: Get a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Category'
      summary: Get an asset category
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Category Title
        in: path
        name: categoryTitle
        required: true
        type: string
      - description: Category object
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/types.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Category'
        "500":
          description: Internal Server Error
      summary: Update an asset category
  /groups:
    get:
      description: List all groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Group'
            type: array
      summary: List asset groups
    post:
      consumes:
      - application/json
      description: Create a group
      parameters:
      - description: Group object
        in: body
        name: group
        required: true
        schema:
          $ref: '#/definitions/types.Group'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Group'
      summary: Create an asset group
  /groups/{groupTitle}:
    delete:
      description: Delete a group
      parameters:
      - description: Group Title
        in: path
        name: groupTitle
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Delete an asset group
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
