/*
PersonaCMMS API

This is the Personal Computer Maintenance Management System REST API.

API version: 1.0
Contact: greenrivercodelabs@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TypesTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesTask{}

// TypesTask struct for TypesTask
type TypesTask struct {
	Instructions *string `json:"instructions,omitempty"`
	Title string `json:"title"`
}

type _TypesTask TypesTask

// NewTypesTask instantiates a new TypesTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesTask(title string) *TypesTask {
	this := TypesTask{}
	this.Title = title
	return &this
}

// NewTypesTaskWithDefaults instantiates a new TypesTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesTaskWithDefaults() *TypesTask {
	this := TypesTask{}
	return &this
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *TypesTask) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypesTask) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *TypesTask) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *TypesTask) SetInstructions(v string) {
	o.Instructions = &v
}

// GetTitle returns the Title field value
func (o *TypesTask) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *TypesTask) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *TypesTask) SetTitle(v string) {
	o.Title = v
}

func (o TypesTask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *TypesTask) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypesTask := _TypesTask{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypesTask)

	if err != nil {
		return err
	}

	*o = TypesTask(varTypesTask)

	return err
}

type NullableTypesTask struct {
	value *TypesTask
	isSet bool
}

func (v NullableTypesTask) Get() *TypesTask {
	return v.value
}

func (v *NullableTypesTask) Set(val *TypesTask) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesTask) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesTask(val *TypesTask) *NullableTypesTask {
	return &NullableTypesTask{value: val, isSet: true}
}

func (v NullableTypesTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


